# Generated by Django 5.1.1 on 2024-10-07 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
