# Generated by Django 5.1.1 on 2024-10-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
