# Generated by Django 5.1.1 on 2024-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0013_alter_jobapplication_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewed_jobs',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='remote.job'),
        ),
    ]
