# Generated by Django 5.1.1 on 2024-10-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0014_profile_viewed_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='remote.job'),
        ),
    ]
